const location = require('../models/LocationModel');
const factory = require("../utils/handlerFactory");
const catchAsync = require("../utils/catchAsync");
exports.getAllLocation = factory.getAll(location);
exports.getLocation = factory.getOne(location);
exports.updateLocation = factory.updateOne(location);
exports.createLocation = factory.createOne(location);
exports.deleteLocation = factory.deleteOne(location);
exports.getAllRegion = factory.getField(location, "region");
